language: python
sudo: required
dist: trusty
group: deprecated-2017Q2
matrix:
    include:
        - python: 2.7
        - python: 3.5
install:
    - source ci/install.sh
script:
    - bash ci/test.sh
notifications:
    email: false
